### ISSUE TITLE
Doesn't work properly for scoped packages

### ISSUE THREAD

**Issue by lzilioli** [sindresorhus/package-json#5]
I'm using the `latest-version` package to fetch the latest version of one of my modules that is published to an internal Docker-containerized sinopia repo. It relies on `package-json` to fetch the latest package from npm.

The url that gets built by this `package-json` for purposes of fetching the package file is incorrect in my case.

If the `package-json` method is called with:

```
name      @scope/package-name
version   latest
```

The value of `url` winds up being `http://<npm server>@scope/package-name`. (note the lack of a slash after the server, as well as the unencoded slash in the`scope/package-name).

Our Sinopia repo is unable to locate the package unless the url is of the format `http://<npm server>/@scope%2fpackage-name`. Is this a bug in this module? Or would you consider it to be a bug with out Sinopia server?

**Comment by lzilioli** [comment]
The above patch fixes the issue for me. I'd be willing to add tests, etc, etc. and submit a formal pull request, but am not familiar with the process of contributing to the project. Please advise.

**Comment by sindresorhus** [comment]
Yes, PR appreciated :)

No specific process other than the normal: include a test, have a useful commit and PR title, try to follow the existing code style.

**Comment by lzilioli** [comment]
@sindresorhus My initial fix broke all of the tests (but fixed my use-case :P). I'm working on a branch that addresses the issue, doesn't break the existing tests, and adds tests for scoped packages, however I am not aware of any publicly accessible scoped packages on npm to test against (similar to how you currently test against pageres). Thus, I can't say how npm behaves in this case.

Curiously, Sinopia is responding with different content than the unit tests are expecting, so there are certainly differences between the two npm servers.

Here's the JSON that comes back from npm while executing the unit tests:

```
{ _id: 'pageres',
  _rev: '51-3547ffc03452a9162ddc493844361a50',
  name: 'pageres',
  description: 'Capture website screenshots',
  'dist-tags': { latest: '2.0.0' },
  versions: 
   { '0.1.0': 
      { name: 'pageres',
        version: '0.1.0',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.1.0',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.1.1': 
      { name: 'pageres',
        version: '0.1.1',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.1.1',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.1.2': 
      { name: 'pageres',
        version: '0.1.2',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.1.2',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.1.3': 
      { name: 'pageres',
        version: '0.1.3',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.1.3',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.1.4': 
      { name: 'pageres',
        version: '0.1.4',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.1.4',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.2.0': 
      { name: 'pageres',
        version: '0.2.0',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.2.0',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.3.25',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.2.1': 
      { name: 'pageres',
        version: '0.2.1',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.2.1',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.4.2',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.2.2': 
      { name: 'pageres',
        version: '0.2.2',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.2.2',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.4.2',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.2.3': 
      { name: 'pageres',
        version: '0.2.3',
        description: 'Get screenshots of websites in different resolutions',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.2.3',
        dist: [Object],
        _from: '.',
        _npmVersion: '1.4.2',
        _npmUser: [Object],
        maintainers: [Object],
        directories: {} },
     '0.3.0': 
      { name: 'pageres',
        version: '0.3.0',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.3.0',
        _shasum: '2153404223244089af18a8cde2623ea5e16b722d',
        _from: '.',
        _npmVersion: '1.4.9',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '0.4.0': 
      { name: 'pageres',
        version: '0.4.0',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'abda8db6fe1e4f040ccfb18137abcaa937a09a27',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.4.0',
        _shasum: '7596ffd865dc2468a5183dab0ae91e60b033ec48',
        _from: '.',
        _npmVersion: '1.4.14',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '0.4.1': 
      { name: 'pageres',
        version: '0.4.1',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'dd8155451ea027a6d24e098e44cc4a62b03b4abb',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@0.4.1',
        _shasum: '7321e800166ed9d46117325d6d51520dec8b47df',
        _from: '.',
        _npmVersion: '1.4.14',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.0.0': 
      { name: 'pageres',
        version: '1.0.0',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: '451852c7f94addfb8a98102880e97e311facf7d5',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.0.0',
        _shasum: 'a3e8a59219e5d22ae713c2e057143666e5d516e5',
        _from: '.',
        _npmVersion: '2.1.2',
        _nodeVersion: '0.10.32',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.0.1': 
      { name: 'pageres',
        version: '1.0.1',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'a95351ee6bfc5a9f7641e07ab5f2b18d863c018e',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.0.1',
        _shasum: 'c5d11dbc8523526df311d271731042f0c3994062',
        _from: '.',
        _npmVersion: '2.1.2',
        _nodeVersion: '0.10.32',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.1.0': 
      { name: 'pageres',
        version: '1.1.0',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'e7702e26e9da7d329d59ecd7af801c8a2a0be5d9',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.1.0',
        _shasum: '11fa89444d377941971d092d756f40c12337fc79',
        _from: '.',
        _npmVersion: '2.1.16',
        _nodeVersion: '0.10.32',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.2.0': 
      { name: 'pageres',
        version: '1.2.0',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        preferGlobal: true,
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: '3c7333fd53a0046ae86b43ff67722b7b93adccf6',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.2.0',
        _shasum: 'd62b6d0a006befd2b78dd1efc8a84a49005859c6',
        _from: '.',
        _npmVersion: '2.5.1',
        _nodeVersion: '0.12.0',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.2.1': 
      { name: 'pageres',
        version: '1.2.1',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        preferGlobal: true,
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: '328f9639ccd08de0fcf648d17b3512cedcc7ed01',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.2.1',
        _shasum: '52ab09c737735bfce9ca3054910434a30632c26c',
        _from: '.',
        _npmVersion: '2.5.1',
        _nodeVersion: '0.12.0',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.2.2': 
      { name: 'pageres',
        version: '1.2.2',
        description: 'Responsive website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        preferGlobal: true,
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: '7aea27e18fbf302e6868dfe366643708ed3dae73',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@1.2.2',
        _shasum: '380fc4f29796d2c2b724a286bd90b8ce37b612ab',
        _from: '.',
        _npmVersion: '2.7.1',
        _nodeVersion: '1.6.2',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.3.0': 
      { name: 'pageres',
        version: '1.3.0',
        description: 'Capture website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        preferGlobal: true,
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: '6274e085c933052f89b33deb40c2243f15f7695f',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres#readme',
        _id: 'pageres@1.3.0',
        _shasum: '4f1c005e7a7d92cbbe9cec254c26ff545196bc30',
        _from: '.',
        _npmVersion: '2.8.3',
        _nodeVersion: '0.12.2',
        _npmUser: [Object],
        maintainers: [Object],
        dist: [Object],
        directories: {} },
     '1.4.0': 
      { name: 'pageres',
        version: '1.4.0',
        description: 'Capture website screenshots',
        license: 'MIT',
        repository: [Object],
        bin: [Object],
        preferGlobal: true,
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'ceefc29076135898d3642d2a6c0a19650cacec9c',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres#readme',
        _id: 'pageres@1.4.0',
        _shasum: 'f5de057ed45c38a306f81f85fcb1fc9137ef89af',
        _from: '.',
        _npmVersion: '2.10.0',
        _nodeVersion: '0.12.3',
        _npmUser: [Object],
        dist: [Object],
        maintainers: [Object],
        directories: {} },
     '2.0.0': 
      { name: 'pageres',
        version: '2.0.0',
        description: 'Capture website screenshots',
        license: 'MIT',
        repository: [Object],
        author: [Object],
        engines: [Object],
        scripts: [Object],
        files: [Object],
        keywords: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        gitHead: 'f94c207211aa83b3281b7a14ac47816c1eb82675',
        bugs: [Object],
        homepage: 'https://github.com/sindresorhus/pageres',
        _id: 'pageres@2.0.0',
        _shasum: '74c3f963e2037392980b731e15200eca8aeb572b',
        _from: '.',
        _npmVersion: '2.10.1',
        _nodeVersion: '0.12.4',
        _npmUser: [Object],
        dist: [Object],
        maintainers: [Object],
        directories: {} } },
  readme: '# ![pageres](media/promo.png)\n\n[![Build Status](https://travis-ci.org/sindresorhus/pageres.svg?branch=master)](https://travis-ci.org/sindresorhus/pageres) [![Coverage Status](https://coveralls.io/repos/sindresorhus/pageres/badge.svg?branch=master)](https://coveralls.io/r/sindresorhus/pageres?branch=master)\n\nCapture screenshots of websites in various resolutions. A good way to make sure your websites are responsive. It\'s speedy and generates 100 screenshots from 10 different websites in just over a minute. It can also be used to render SVG images.\n\n*See [pageres-cli](https://github.com/sindresorhus/pageres-cli) for the command-line version.*\n\n\n## Install\n\n```\n$ npm install --save pageres\n```\n\n*PhantomJS, which is used for generating the screenshots, is installed automagically, but in some [rare cases](https://github.com/Obvious/phantomjs/issues/102) it might fail to and you\'ll get an `Error: spawn EACCES` error. [Download](http://phantomjs.org/download.html) PhantomJS manually and reinstall pageres if that happens.*\n\n\n## Usage\n\n```js\nvar Pageres = require(\'pageres\');\n\nvar pageres = new Pageres({delay: 2})\n\t.src(\'yeoman.io\', [\'480x320\', \'1024x768\', \'iphone 5s\'], {crop: true})\n\t.src(\'todomvc.com\', [\'1280x1024\', \'1920x1080\'])\n\t.dest(__dirname);\n\npageres.run(function (err) {\n\tconsole.log(\'done\');\n});\n```\n\n## API\n\n### Pageres([options])\n\n#### options\n\n##### delay\n\nType: `number` *(seconds)*  \nDefault: `0`\n\nDelay capturing the screenshot.\n\nUseful when the site does things after load that you want to capture.\n\n##### crop\n\nType: `boolean`  \nDefault: `false`\n\nCrop to the set height.\n\n##### cookies\n\nType: `array` of `string`, `object`\n\nA string with the same format as a [browser cookie](http://en.wikipedia.org/wiki/HTTP_cookie) or an object of what [`phantomjs.addCookie`](http://phantomjs.org/api/phantom/method/add-cookie.html) accepts.\n\n###### Tip\n\nGo to the website you want a cookie for and copy-paste it from Dev Tools.\n\n##### filename\n\nType: `string`\n\nDefine a customized filename using [Lo-Dash templates](http://lodash.com/docs#template).  \nFor example `<%= date %> - <%= url %>-<%= size %><%= crop %>`.\n\nAvailable variables:\n\n- `url`: The URL in [slugified](https://github.com/ogt/slugify-url) form, eg. `http://yeoman.io/blog/` becomes `yeoman.io!blog`\n- `size`: Specified size, eg. `1024x1000`\n- `width`: Width of the specified size, eg. `1024`\n- `height`: Height of the specified size, eg. `1000`\n- `crop`: Outputs `-cropped` when the crop option is true\n- `date`: The current date (Y-M-d), eg. 2015-05-18\n- `time`: The current time (h-m-s), eg. 21-15-11\n\n##### selector\n\nType: `string`\n\nCapture a specific DOM element.\n\n##### hide\n\nType: `array`\n\nHide an array of DOM elements.\n\n##### username\n\nType: `string`\n\nUsername for authenticating with HTTP auth.\n\n##### password\n\nType: `string`\n\nPassword for authenticating with HTTP auth.\n\n##### scale\n\nType: `number`  \nDefault: `1`\n\nScale webpage `n` times.\n\n##### format\n\nType: `string`  \nDefault: `png`  \nValues: `png`, `jpg`\n\nImage format.\n\n##### userAgent\n\nType: `string`\n\nCustom user agent.\n\n\n### pageres.src(url, sizes, options)\n\nAdd a page to screenshot.\n\n#### url\n\n*Required*  \nType: `string`\n\nURL or local path to the website you want to screenshot.\n\n#### sizes\n\n*Required*  \nType: `array`\n\nUse a `<width>x<height>` notation or a keyword.\n\nA keyword is a version of a device from [this list](http://viewportsizes.com).\nYou can also pass in the `w3counter` keyword to use the ten most popular\nresolutions from [w3counter](http://www.w3counter.com/globalstats.php).\n\n#### options\n\nType: `object`\n\nOptions set here will take precedence over the ones set in the constructor.\n\n### pageres.dest(directory)\n\nSet the destination directory.\n\n#### directory\n\nType: `string`\n\n### pageres.run(callback)\n\nRun pageres.\n\n#### callback(error, [items])\n\nType: `function`\n\nIf you don\'t set a `dest()` you\'ll get `items` in this callback, which is an array of streams.\n\n### pageres.on(\'warn\', callback)\n\nWarnings with eg. page errors.\n\n\n## Task runners\n\nCheck out [grunt-pageres](https://github.com/sindresorhus/grunt-pageres) if you\'re using grunt.\n\nFor gulp or broccoli, just use the below API directly. No need for a wrapper plugin.\n\n\n## Built with Pageres\n\n- [Break Shot](https://github.com/rcdigital/break-shot) - Desktop app for capturing screenshots of responsive websites.\n\n\n## Team\n\n[![Sindre Sorhus](http://gravatar.com/avatar/d36a92237c75c5337c17b60d90686bf9?s=144)](http://sindresorhus.com) | [![Kevin Mårtensson](http://gravatar.com/avatar/48fa294e3cd41680b80d3ed6345c7b4d?s=144)](https://github.com/kevva)\n---|---\n[Sindre Sorhus](http://sindresorhus.com) | [Kevin Mårtensson](https://github.com/kevva)\n\n\n## License\n\nMIT © [Sindre Sorhus](http://sindresorhus.com)\n',
  maintainers: 
   [ { name: 'sindresorhus', email: 'sindresorhus@gmail.com' },
     { name: 'kevva', email: 'kevinmartensson@gmail.com' } ],
  time: 
   { modified: '2015-06-21T14:06:12.211Z',
     created: '2014-02-07T18:17:46.737Z',
     '0.1.0': '2014-02-07T18:17:46.737Z',
     '0.1.1': '2014-02-07T18:41:37.003Z',
     '0.1.2': '2014-02-08T13:15:32.084Z',
     '0.1.3': '2014-02-11T10:57:58.019Z',
     '0.1.4': '2014-02-11T14:06:08.582Z',
     '0.2.0': '2014-02-11T18:12:30.311Z',
     '0.2.1': '2014-02-14T09:07:45.470Z',
     '0.2.2': '2014-02-14T09:07:56.143Z',
     '0.2.3': '2014-02-14T09:12:01.009Z',
     '0.3.0': '2014-06-30T17:03:33.681Z',
     '0.4.0': '2014-08-01T20:39:30.433Z',
     '0.4.1': '2014-08-11T13:57:14.814Z',
     '1.0.0': '2014-10-13T10:17:39.741Z',
     '1.0.1': '2014-10-21T13:19:12.566Z',
     '1.1.0': '2014-12-25T17:27:01.003Z',
     '1.2.0': '2015-02-24T08:21:21.997Z',
     '1.2.1': '2015-03-02T16:20:39.190Z',
     '1.2.2': '2015-03-24T22:13:31.618Z',
     '1.3.0': '2015-04-20T09:01:30.098Z',
     '1.4.0': '2015-05-19T22:31:54.571Z',
     '2.0.0': '2015-06-21T14:06:12.211Z' },
  readmeFilename: 'readme.md',
  users: 
   { zhangskills: true,
     xtopher: true,
     goliatone: true,
     lardconcepts: true,
     'theodor.lindekaer': true,
     ericwbailey: true,
     tomekf: true,
     'y-a-v-a': true,
     miclgael: true,
     sewillia: true,
     tonydieu: true },
  homepage: 'https://github.com/sindresorhus/pageres',
  keywords: 
   [ 'page',
     'website',
     'site',
     'web',
     'url',
     'resolution',
     'size',
     'screenshot',
     'screenshots',
     'screengrab',
     'screen',
     'snapshot',
     'shot',
     'responsive',
     'gulpfriendly',
     'phantom',
     'phantomjs',
     'image',
     'svg',
     'render',
     'html',
     'headless',
     'capture',
     'pic',
     'picture',
     'png',
     'jpg',
     'jpeg' ],
  repository: { type: 'git', url: 'https://github.com/sindresorhus/pageres' },
  author: 
   { name: 'Sindre Sorhus',
     email: 'sindresorhus@gmail.com',
     url: 'sindresorhus.com' },
  bugs: { url: 'https://github.com/sindresorhus/pageres/issues' },
  license: 'MIT',
  _attachments: {} }
```

And here's the JSON I get back when executing the unit tests on my office VPN where I can hit our Sinopia repo:

```
{ name: '@rmn/roux-cli',
  versions: 
   { '0.1.0': 
      { name: '@rmn/roux-cli',
        version: '0.1.0',
        description: 'The Roux command line interface',
        author: [Object],
        repository: [Object],
        publishConfig: [Object],
        config: [Object],
        preferGlobal: true,
        bin: [Object],
        scripts: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        readmeFilename: 'README.md',
        gitHead: '3a1b7fd537a8f36e7840729e648bd20e31fb57b7',
        _id: '@rmn/roux-cli@0.1.0',
        _shasum: '577454dde4f2b793b23aae3188f1c4f29189cf7b',
        _from: '.',
        _npmVersion: '2.11.2',
        _nodeVersion: '0.10.38',
        _npmUser: {},
        dist: [Object] },
     '0.1.1': 
      { name: '@rmn/roux-cli',
        version: '0.1.1',
        description: 'The Roux command line interface',
        author: [Object],
        repository: [Object],
        publishConfig: [Object],
        config: [Object],
        preferGlobal: true,
        bin: [Object],
        scripts: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        readmeFilename: 'README.md',
        gitHead: '16ae1ca738f86fea24e891d87a8996bc2a901a0f',
        _id: '@rmn/roux-cli@0.1.1',
        _shasum: '9c714ea4f5297f5087d31c689b8276e505614c65',
        _from: '.',
        _npmVersion: '2.11.2',
        _nodeVersion: '0.10.38',
        _npmUser: {},
        dist: [Object] },
     '0.1.2': 
      { name: '@rmn/roux-cli',
        version: '0.1.2',
        description: 'The Roux command line interface',
        author: [Object],
        repository: [Object],
        publishConfig: [Object],
        config: [Object],
        preferGlobal: true,
        bin: [Object],
        scripts: [Object],
        dependencies: [Object],
        devDependencies: [Object],
        readmeFilename: 'README.md',
        gitHead: 'bbc2ee4b1442241996c91c0342416d0298b49f0a',
        _id: '@rmn/roux-cli@0.1.2',
        _shasum: 'ecd27f2dd956b40a66b2d6c5254e23db6ca6e9fe',
        _from: '.',
        _npmVersion: '2.11.2',
        _nodeVersion: '0.10.38',
        _npmUser: {},
        dist: [Object] } },
  'dist-tags': { latest: '0.1.2' },
  _rev: '9-7aade2ddafbdd7af',
  readme: '<readme contents>',
  _attachments: {} }
```

Notice how the description is missing from the top level from Sinopia? This causes the `get a single field` test case to fail for my scoped package. Also note the lack of an `_id` field. This causes the `should get the package.json main entry when no version is specified` test case to fail. It's likely that these discrepancies are caused by Sinopia and not npm.

I'm not sure that we will be able to write unit tests for scoped packages, unless some are publicly available, but the commit I am about to push seems to properly fix my issue without breaking your unit tests. If we can't figure out how to test scoped packages, the changes to test.js should be reverted, and this is probably good to go depending on if we think its safe to call `encodeURIComponent`. Might want to do a major rev just in case?

**Comment by sindresorhus** [comment]
> however I am not aware of any publicly accessible scoped packages on npm to test against (similar to how you currently test against pageres).

https://www.npmjs.com/package/@sindresorhus/df

**Comment by lzilioli** [comment]
@sindresorhus I tweaked the unit test on my issue-5 branch to point to `@sindresorhus/df`, but one of the test cases is still failing: https://github.com/lzilioli/package-json/tree/issue-5

Do you mind taking a look?

**Comment by sindresorhus** [comment]
Do a PR, easier to review ;)

**Comment by destroyerofbuilds** [comment]
@lzilioli this issue looks like a regression introduced by de39fa84f971ed3f2dd9bd796657fbd8228c47f0, which removed `encodeURIComponent`.

Also, on a note related to your `getCleanRegistryUrl` method, I don't believe you need it. I believe that issue was resolved as part of [this pull request](https://github.com/sindresorhus/registry-url/pull/5) in `registry-url`.

In either case I would love to help review a pull request as I have quite a bit of interest in [scope support](https://github.com/sindresorhus/registry-url/pull/2) for npm.

**Comment by lzilioli** [comment]
@destroyerofbuilds I should have some time this weekend to revisit this. I will take your above notes into consideration, and get a new commit pushed up when I get a chance.

**Comment by lzilioli** [comment]
I just submitted https://github.com/sindresorhus/package-json/pull/6 integrating feedback from @destroyerofbuilds. There is still an issue with one of the test cases on my branch. I would love some help tracking the issue down.

**Comment by ljharb** [comment]
yay, thanks!

**Comment by ljharb** [comment]
@sindresorhus can you also bump `latest-version`, since `package-json` was a major bump?

**Comment by sindresorhus** [comment]
@ljharb Already done.

**Comment by ljharb** [comment]
I just did `npm install -g latest-version` and now `which latest-version` isn't found. It appears there's no "bin" field in `latest-version`'s `package.json`?
